# credo:disable-for-this-file Credo.Check.Refactor.ModuleDependencies
defmodule FlickWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :flick

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_flick_key",
    signing_salt: "TsxSgot/",
    same_site: "Lax"
  ]

  # A full ballot edit is about 50 KB, so 1 MB leaves room while bounding what
  # an anonymous client can send in one WebSocket event. Bandit caps messages
  # split across frames separately, under `websocket_options` in
  # `config/config.exs`. Long-poll has no such setting and stays at `read_body`'s
  # 8 MB default.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], max_frame_size: 1_000_000],
    longpoll: [connect_info: [session: @session_options]]

  # Serve Prometheus metrics at "/metrics". It comes before the code reloader
  # and `Plug.Telemetry`, so requests to it don't trigger repo checks or show
  # up in the HTTP metrics.
  plug :prom_ex_metrics

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :flick,
    gzip: not code_reloading?,
    only: FlickWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :flick
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FlickWeb.Router

  # A function plug, so the endpoint refers to `FlickWeb.PromEx` only at
  # runtime. As an option to `plug PromEx.Plug`, the alias would become a
  # compile-time dependency, which `mix precommit`'s xref check rejects.
  defp prom_ex_metrics(conn, _opts) do
    PromEx.Plug.call(conn, PromEx.Plug.init(prom_ex_module: FlickWeb.PromEx))
  end
end
