version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      elixir-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
