# This Docker Compose file is intended for local development and does not impact
# any production environments.
#
# From the root of the project run:
#
# $ docker compose up -d
#
# $ docker compose down -d
#
# FUTURE ENHANCEMENTS IDEAS:
# - We could consider using a `https://hub.docker.com/r/postgis/postgis/`
#   version of the database image to better align with what will be seen in
#   production on Render.

services:
  db:
    image: postgres:17
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  loki:
    # TODO: Consider using a newer version of Loki.
    image: grafana/loki:2.9.3
    configs:
      - source: loki
        target: /etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.3
    deploy:
      mode: global
    configs:
      - source: promtail
        target: /etc/promtail/config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  grafana:
    image: grafana/grafana:9.5.15
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasource.yml
    volumes:
      - grafana-storage:/var/lib/grafana

  alloy:
    image: grafana/alloy:v1.1.1
    configs:
      - source: alloy
        target: /etc/alloy/config.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9090:9090"
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prometheus-data:/prometheus

configs:
  prometheus:
    file: ./instrumentation/prometheus/local.yaml
  alloy:
    file: ./instrumentation/alloy/local.alloy
  loki:
    file: ./instrumentation/loki/local.yaml
  promtail:
    file: ./instrumentation/promtail/local.yaml
  grafana_datasources:
    file: ./instrumentation/grafana/datasources/datasources.yaml

volumes:
  grafana-storage:
  db_data:
  prometheus-data:
