# in instrumentation/loki/local.yaml

# TODO: Setup authentication.
auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: loki
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks
