import Config

config :flick, FlickWeb.Endpoint,
  # https://hexdocs.pm/phoenix/using_ssl.html#hsts
  # FIXME: Restore this in the future.
  # https://github.com/zorn/flick/issues/85
  # force_ssl: [hsts: true]

  # Note we also include the path to a cache manifest
  # containing the digested version of static files. This
  # manifest is generated by the `mix assets.deploy` task,
  # which you should run after static files are built and
  # before starting your production server.
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Flick.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
