{
 "title": "Flick - PromEx PhoenixLiveView Dashboard",
 "description": "All the data that is presented here is captured by the PromEx Phoenix LiveView plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/phoenix_live_view.ex)",
 "tags": [
  "PromEx",
  "Phoenix LiveView",
  "flick"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Prometheus Job",
    "query": "label_values(flick_prom_ex_prom_ex_status_info, job)"
   },
   {
    "name": "instance",
    "label": "Application Instance",
    "query": "label_values(flick_prom_ex_prom_ex_status_info{job=\"$job\"}, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mount Callback Success Rate (last 24h)",
   "type": "stat",
   "description": "A percentage of mount callbacks that successfully executed.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flick_prom_ex_phoenix_live_view_mount_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) / \n(\n  sum(increase(flick_prom_ex_phoenix_live_view_mount_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) + \n  (sum(increase(flick_prom_ex_phoenix_live_view_mount_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) or vector(0))\n)"
    }
   ]
  },
  {
   "title": "Total LiveView Mounts (Last 24h)",
   "type": "stat",
   "description": "The amount of LiveView mounts that have occurred in the last 24 hours.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(flick_prom_ex_phoenix_live_view_mount_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) or vector(0)) + (sum(increase(flick_prom_ex_phoenix_live_view_mount_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) or vector(0))"
    }
   ]
  },
  {
   "title": "Handle Event Callback Success Rate (last 24h)",
   "type": "stat",
   "description": "A percentage of handle_event callbacks that successfully executed.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flick_prom_ex_phoenix_live_view_handle_event_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) / \n(\n  sum(increase(flick_prom_ex_phoenix_live_view_handle_event_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) + \n  (sum(increase(flick_prom_ex_phoenix_live_view_handle_event_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) or vector(0))\n)"
    }
   ]
  },
  {
   "title": "Total LiveView Handle Events (Last 24h)",
   "type": "stat",
   "description": "The amount of LiveView handle_events that have occurred in the last 24 hours.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(flick_prom_ex_phoenix_live_view_handle_event_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) or vector(0)) + (sum(increase(flick_prom_ex_phoenix_live_view_handle_event_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[24h])) or vector(0))"
    }
   ]
  },
  {
   "title": "Mount Callback Success Rate (last 1h)",
   "type": "stat",
   "description": "A percentage of mount callbacks that successfully executed.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flick_prom_ex_phoenix_live_view_mount_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) / \n(\n  sum(increase(flick_prom_ex_phoenix_live_view_mount_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) + \n  (sum(increase(flick_prom_ex_phoenix_live_view_mount_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) or vector(0))\n)"
    }
   ]
  },
  {
   "title": "Total LiveView Mounts (Last 1h)",
   "type": "stat",
   "description": "The amount of LiveView mounts that have occurred in the last hour.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(flick_prom_ex_phoenix_live_view_mount_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) or vector(0)) + (sum(increase(flick_prom_ex_phoenix_live_view_mount_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) or vector(0))"
    }
   ]
  },
  {
   "title": "Handle Event Callback Success Rate (last 1h)",
   "type": "stat",
   "description": "A percentage of handle event callbacks that successfully executed.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flick_prom_ex_phoenix_live_view_handle_event_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) / \n(\n  sum(increase(flick_prom_ex_phoenix_live_view_handle_event_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) + \n  (sum(increase(flick_prom_ex_phoenix_live_view_handle_event_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) or vector(0))\n)"
    }
   ]
  },
  {
   "title": "Total LiveView Handle Events (Last 1h)",
   "type": "stat",
   "description": "The amount of LiveView handle_events that have occurred in the last hour.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(flick_prom_ex_phoenix_live_view_handle_event_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) or vector(0)) + (sum(increase(flick_prom_ex_phoenix_live_view_handle_event_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[1h])) or vector(0))"
    }
   ]
  },
  { "title": "Mount Callback Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average Execution Time",
   "type": "graph",
   "description": "The average time it took to complete the mount callback function.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(flick_prom_ex_phoenix_live_view_mount_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\"}[$interval])) by(action, module) / sum(irate(flick_prom_ex_phoenix_live_view_mount_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[$interval])) by(action, module)",
     "legendFormat": "({{ action }}) {{ module }}"
    }
   ]
  },
  {
   "title": "Average Exception Execution Time",
   "type": "graph",
   "description": "The average time it took to get through the mount callback function when an error was encountered.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(flick_prom_ex_phoenix_live_view_mount_exception_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\"}[$interval])) by(action, module, kind, reason) / sum(irate(flick_prom_ex_phoenix_live_view_mount_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[$interval])) by(action, module, kind, reason)",
     "legendFormat": "({{ action }}) {{ module }} :: ({{kind}} -> {{reason}})"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "heatmap",
   "description": "A heatmap showing the time it took to get through the mount callback.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(flick_prom_ex_phoenix_live_view_mount_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Exception Execution Time",
   "type": "heatmap",
   "description": "A heatmap showing the time it took to get through the mount callback when an exception was encountered.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(flick_prom_ex_phoenix_live_view_mount_exception_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Handle Event Callback Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Average Execution Time",
   "type": "graph",
   "description": "The average time it took to complete the handle_event callback function.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(flick_prom_ex_phoenix_live_view_handle_event_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\"}[$interval])) by(action, module, event) / sum(irate(flick_prom_ex_phoenix_live_view_handle_event_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[$interval])) by(action, module, event)",
     "legendFormat": "({{ action }}) {{ module }} :: {{ event }}"
    }
   ]
  },
  {
   "title": "Average Exception Execution Time",
   "type": "graph",
   "description": "The average time it took to get through the handle_event callback function.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(flick_prom_ex_phoenix_live_view_handle_event_exception_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\"}[$interval])) by(event, action, module, kind, reason) / sum(irate(flick_prom_ex_phoenix_live_view_handle_event_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[$interval])) by(event, action, module, kind, reason)",
     "legendFormat": "({{ action }}) {{ module }} :: {{event}} ({{kind}} -> {{reason}})"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "heatmap",
   "description": "A heatmap showing the time it took to get through the mount callback.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(irate(flick_prom_ex_phoenix_live_view_handle_event_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Exception Execution Time",
   "type": "heatmap",
   "description": "A heatmap showing the time it took to get through the handle_event callback when an exception was encountered.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(irate(flick_prom_ex_phoenix_live_view_handle_event_exception_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}