name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
# Cancel any in-progress instances of this workflow when this instance is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality_checks:
    name: Formatting, Credo, and Unused Deps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          build-app: false

      - name: Check for unused deps
        run: mix deps.unlock --check-unused

      - name: Check code formatting
        run: mix format --check-formatted
        if: always()

      - name: Run Credo
        run: mix credo --strict
        if: always()

      - name: Check for compile-time dependencies
        run: mix xref graph --label compile-connected --fail-above 0
        if: always()

      - name: Check for security vulnerabilities in Phoenix project
        run: mix sobelow --config
        if: always()
